- hosts: all
  gather_facts: no
  tasks:

  - name: install apache2 & php services
    apt:
      name: 
      - apache2
      - libapache2-mod-php
      state: latest
      update_cache: yes

  - name: Start service apache2, if not started
    ansible.builtin.service:
      name: apache2
      state: started  

