- hosts: all
  tasks:
  - name: update repo
    apt:
      update_cache: yes

  - name: install apache2
    apt:
      name: apache2
      state: latest
  - name: add php lib support for apache
    apt:
      name: libapache2-mod-php
      state: latest
