- hosts: all
  gather_facts: no
  tasks:
  - name: update repo
    apt:
      update_cache: yes

  - name: install apache2
    apt:
      name: apache2
      state: latest

  - name: Start service apache2, if not started
    ansible.builtin.service:
      name: apache2
      state: started  

  - name: add php lib support for apache
    apt:
      name: libapache2-mod-php
      state: latest
