- hosts: all
  gather_facts: no
  tasks:

  - name: install apache2 & php services
    package:
      name: 
      - "{{apache_package}}"
      - "{{php_package}}"
      state: latest
      update_cache: yes

  - name: Start service apache2, if not started
    service:
      name: apache2
      state: started  

